export const CHANGE_FOODS="CHANGE_FOODS"
export const GET_FOODS_SUCCESS="GET_FOODS_SUCCESS"

export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"

export const HANDLE_CHANGE="HANDLE_CHANGE"
export const HANDLE_SUBMİT="HANDLE_SUBMİT"

export const ADD_TO_PROFILE="ADD_TO_PROFILE"